//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Vendor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_VendorCreation
    {
        public decimal RequestID { get; set; }
        public string RequestType { get; set; }
        public string Resion { get; set; }
        public string BusinessName { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string CompanyType { get; set; }
        public string NTNNo { get; set; }
        public string TaxRegNo { get; set; }
        public string PaymentCurrency { get; set; }
        public Nullable<bool> RegNA { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }
        public string PaymentMethod { get; set; }
        public string NatureOfWork { get; set; }
        public string WHoldingTax { get; set; }
        public string Classification { get; set; }
        public string Qualification { get; set; }
        public Nullable<bool> QuestionnaireCompleted { get; set; }
        public string PeriodUpto { get; set; }
        public string BankAddress { get; set; }
        public string AccountNoIBAN { get; set; }
        public string RoutingNo { get; set; }
        public string SwiftCode { get; set; }
        public string BenificaryName { get; set; }
        public string PaymentTerms { get; set; }
        public string Status { get; set; }
        public string EmailSent { get; set; }
        public Nullable<System.DateTime> EmailSentDate { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
