//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Vendor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_VendorAttachment
    {
        public int Id { get; set; }
        public string RequestId { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
