//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Vendor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_Vendor_Items
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public string Category { get; set; }
        public string Enable { get; set; }
    }
}
