//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_Vendor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Attachment
    {
        public decimal ID { get; set; }
        public Nullable<decimal> Request_ID { get; set; }
        public string FileName { get; set; }
    }
}
